const err = {
  NO_VIDEO_SPECIFIED: 'NO_VIDEO_SPECIFIED',
  EXCEED_VIDEO_TIME_LIMIT: 'EXCEED_VIDEO_TIME_LIMIT',
  VIDEO_FORMAT_NOT_SUPPORTED: 'VIDEO_FORMAT_NOT_SUPPORTED',
  VIDEO_IS_CONVERTING: 'VIDEO_IS_CONVERTING',
  MEDIA_NOT_SUPPORTED: 'MEDIA_NOT_SUPPORT'
};

export default err;
