export const NOTIFICATIONS = {
  POST_MEDIA_SUCCESS: 'POST_MEDIA_SUCCESS',
  UPDATE_MEDIA_SUCCESS: 'UPDATE_MEDIA_SUCCESS',
  DELETE_MEDIA_SUCCESS: 'DELETE_MEDIA_SUCCESS',
  APPLY_FILTERS_SUCCESS: 'APPLY_FILTERS_SUCCESS'
}
