export const NOTIFICATIONS = {
  POST_MEDIA_SUCCESS: 'POST_MEDIA_SUCCESS',
  UPDATE_MEDIA_SUCCESS: 'UPDATE_MEDIA_SUCCESS',
  DELETE_MEDIA_SUCCESS: 'DELETE_MEDIA_SUCCESS',
  UPDATE_PROFILE_PICTURE_SUCCESS: 'UPDATE_PROFILE_PICTURE_SUCCESS',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  APPLY_FILTERS_SUCCESS: 'APPLY_FILTERS_SUCCESS',
  SHARE_SUCCESS: 'SHARE_SUCCESS'
}
